const V = {
  bunny: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  dream: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  sintel: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  tears: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  blazes: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  escapes: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  fun: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  joy: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
  melt: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  subaru: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
  gti: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
  grand: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
};
const pic = (seed) => `https://picsum.photos/seed/${seed}/400/600`;
const wide = (seed) => `https://picsum.photos/seed/${seed}/1280/720`;

function ep(title, dur, seed, video) {
  return { title, dur, thumb: wide(seed), video, desc: 'A thrilling chapter packed with twists, heart and jaw-dropping moments.' };
}

export const VIDEOS = V;

export const catalog = [
  // ANIME
  { id: 'anime-1', title: 'Blade of the Crimson Moon', category: 'anime', genres: ['Action', 'Fantasy', 'Adventure'], year: 2024, rating: 9.1, maturity: 'TV-14', seasons: 2, episodesCount: 24, lang: 'Sub + Dub', trending: 1, featured: true, poster: pic('crimson-moon'), backdrop: wide('crimson-moon-bg'), video: V.sintel, cast: 'Yuki Tanaka, Ren Sato, Aoi Kudo', synopsis: 'A young swordswoman inherits a cursed blade that only awakens under a crimson moon. Hunted by demon clans, she must master its power before it consumes her.', episodes: [ep('S1 E1 — The Moon Bleeds', '24m', 'cm1', V.sintel), ep('S1 E2 — Demon Pact', '24m', 'cm2', V.tears), ep('S1 E3 — Village of Ash', '24m', 'cm3', V.bunny), ep('S1 E4 — The Trial', '24m', 'cm4', V.dream)] },
  { id: 'anime-2', title: 'Neon Ronin', category: 'anime', genres: ['Sci-Fi', 'Cyberpunk', 'Action'], year: 2023, rating: 8.8, maturity: 'TV-MA', seasons: 1, episodesCount: 12, lang: 'Sub + Dub', trending: 2, featured: true, poster: pic('neon-ronin'), backdrop: wide('neon-ronin-bg'), video: V.tears, cast: 'Ken Watanabe-style dub, Mira Chen', synopsis: 'In Neo-Kyoto 2099, a masterless samurai-android takes mercenary jobs while searching for the corporation that wiped his memory.', episodes: [ep('E1 — Static Ghost', '23m', 'nr1', V.tears), ep('E2 — Chrome Katana', '23m', 'nr2', V.blazes), ep('E3 — Black Signal', '23m', 'nr3', V.escapes)] },
  { id: 'anime-3', title: 'Spirits of the Paper Crane', category: 'anime', genres: ['Fantasy', 'Drama', 'Slice of Life'], year: 2024, rating: 8.6, maturity: 'TV-PG', seasons: 1, episodesCount: 13, lang: 'Sub + Dub', trending: 5, poster: pic('paper-crane'), backdrop: wide('paper-crane-bg'), video: V.dream, cast: 'Hana Mori, Daiki Ito', synopsis: 'A shy girl discovers origami cranes that come alive and carry wishes to the spirit world — each wish costs a memory.', episodes: [ep('E1 — One Thousand Wishes', '24m', 'pc1', V.dream), ep('E2 — The Fold', '24m', 'pc2', V.fun)] },
  { id: 'anime-4', title: 'Kaiju Academy', category: 'anime', genres: ['Action', 'Comedy', 'School'], year: 2022, rating: 8.3, maturity: 'TV-14', seasons: 3, episodesCount: 36, lang: 'Dub', trending: 9, poster: pic('kaiju-acad'), backdrop: wide('kaiju-acad-bg'), video: V.bunny, cast: 'Sho Hayami, Riko Tan', synopsis: 'Teenagers who can transform into mini-kaiju attend a secret academy to learn to defend the city — and survive exams.', episodes: [ep('E1 — Enrollment Smash', '22m', 'ka1', V.bunny), ep('E2 — Cafeteria Rumble', '22m', 'ka2', V.joy)] },
  { id: 'anime-5', title: 'The Last Alchemist', category: 'anime', genres: ['Fantasy', 'Mystery', 'Steampunk'], year: 2023, rating: 9.0, maturity: 'TV-14', seasons: 2, episodesCount: 26, lang: 'Sub + Dub', trending: 4, poster: pic('last-alch'), backdrop: wide('last-alch-bg'), video: V.escapes, cast: 'Sora Amamiya, Kaito Fujii', synopsis: 'In a city where alchemy is outlawed, a prodigy forges forbidden alloys to cure her brother — and uncovers a conspiracy of gold.', episodes: [ep('E1 — Lead into Gold', '24m', 'la1', V.escapes), ep('E2 — The Furnace', '24m', 'la2', V.melt)] },
  { id: 'anime-6', title: 'Starlight Ramen Riders', category: 'anime', genres: ['Comedy', 'Food', 'Sci-Fi'], year: 2024, rating: 8.1, maturity: 'TV-G', seasons: 1, episodesCount: 12, lang: 'Dub', poster: pic('ramen'), backdrop: wide('ramen-bg'), video: V.fun, cast: 'Pop Team Voices', synopsis: 'Delivery riders race across galaxies serving magical ramen that grants wild powers to whoever slurps first.', episodes: [ep('E1 — Extra Noodles, Extra Trouble', '20m', 'sr1', V.fun)] },
  // MOVIES
  { id: 'movie-1', title: 'Echoes of Tomorrow', category: 'movie', genres: ['Sci-Fi', 'Thriller'], year: 2024, rating: 8.7, maturity: 'PG-13', duration: '2h 18m', trending: 3, featured: true, poster: pic('echoes'), backdrop: wide('echoes-bg'), video: V.tears, cast: 'Ava Stone, Marcus Reid, Lena Okafor', synopsis: 'A physicist receives voicemails from her future self warning of a catastrophe — but every fix creates a darker timeline.' },
  { id: 'movie-2', title: 'The Midnight Heist', category: 'movie', genres: ['Action', 'Crime', 'Comedy'], year: 2023, rating: 8.2, maturity: 'PG-13', duration: '1h 56m', trending: 6, poster: pic('midnight-heist'), backdrop: wide('midnight-heist-bg'), video: V.blazes, cast: 'Diego Ramos, Priya Nair, Tom Beck', synopsis: 'A retired crew reunites for one impossible casino robbery during a city-wide blackout. Nothing goes to plan. Everything goes wrong hilariously.' },
  { id: 'movie-3', title: 'Whispering Pines', category: 'movie', genres: ['Horror', 'Mystery'], year: 2024, rating: 7.9, maturity: 'R', duration: '1h 48m', poster: pic('pines'), backdrop: wide('pines-bg'), video: V.melt, cast: 'Sarah Lind, Cole Harper', synopsis: 'A podcaster investigating disappearances in a fog-bound forest finds tapes that record events before they happen.' },
  { id: 'movie-4', title: 'Empire of Salt', category: 'movie', genres: ['Drama', 'History', 'Epic'], year: 2023, rating: 8.9, maturity: 'PG-13', duration: '2h 41m', trending: 8,poster: pic('salt'), backdrop: wide('salt-bg'), video: V.subaru, cast: 'Omar Haddad, Elena Petrova', synopsis: 'Two merchant families war over desert trade routes in a sweeping epic of loyalty, betrayal and survival.' },
  { id: 'movie-5', title: 'Zero Gravity Love', category: 'movie', genres: ['Romance', 'Sci-Fi'], year: 2024, rating: 7.6, maturity: 'PG', duration: '1h 52m', poster: pic('zero-g'), backdrop: wide('zero-g-bg'), video: V.joy, cast: 'Mia Park, Jonas Weber', synopsis: 'Two rival astronauts stuck on a space station must cooperate to get home — and keep falling for each other in zero-g.' },
  { id: 'movie-6', title: 'Iron Verdict', category: 'movie', genres: ['Action', 'Drama'], year: 2022, rating: 8.0, maturity: 'R', duration: '2h 5m', poster: pic('iron-verdict'), backdrop: wide('iron-bg'), video: V.gti, cast: 'Dwayne-style lead, Kate Mara-ish', synopsis: 'An ex-fighter turned lawyer enters underground bouts to fund his sister\'s defense in a rigged trial.' },
  // SERIES
  { id: 'series-1', title: 'The Glass Citadel', category: 'series', genres: ['Drama', 'Fantasy', 'Mystery'], year: 2024, rating: 9.3, maturity: 'TV-MA', seasons: 2, episodesCount: 16, trending: 1, featured: true, poster: pic('glass'), backdrop: wide('glass-bg'), video: V.sintel, cast: 'Olivia Grant, Idris Mensah, Sofia Reyes', synopsis: 'Seven noble houses scheme inside a transparent palace where every whisper is seen. A servant girl holds the shard that can shatter it all.', episodes: [ep('S1 E1 — Transparent Lies', '58m', 'gc1', V.sintel), ep('S1 E2 — The Shard', '55m', 'gc2', V.bunny), ep('S1 E3 — Banquet of Knives', '1h', 'gc3', V.tears), ep('S1 E4 — Fracture', '57m', 'gc4', V.dream)] },
  { id: 'series-2', title: 'Hollow Point', category: 'series', genres: ['Crime', 'Thriller'], year: 2023, rating: 8.8, maturity: 'TV-MA', seasons: 3, episodesCount: 24, trending: 7, poster: pic('hollow'), backdrop: wide('hollow-bg'), video: V.grand, cast: 'Ray Delgado, Anna Kim', synopsis: 'A detective with a perfect record takes a case in a town where no crime has been reported in 20 years — because they hide them all.' , episodes: [ep('S1 E1 — Quiet Town', '52m', 'hp1', V.grand), ep('S1 E2 — The Ledger', '50m', 'hp2', V.blazes)] },
  { id: 'series-3', title: 'Mars General', category: 'series', genres: ['Sci-Fi', 'Drama'], year: 2024, rating: 8.5, maturity: 'TV-14', seasons: 1, episodesCount: 8, poster: pic('mars-gen'), backdrop: wide('mars-bg'), video: V.escapes, cast: 'Chris Pine-ish, Zhao Wei', synopsis: 'The first governor of Mars colony faces mutiny, dust storms and Earth politics cutting life support.', episodes: [ep('E1 — Red Soil', '1h', 'mg1', V.escapes)] },
  { id: 'series-4', title: 'The Food Critic', category: 'series', genres: ['Comedy', 'Drama'], year: 2022, rating: 8.4, maturity: 'TV-14', seasons: 4, episodesCount: 32, poster: pic('food-critic'), backdrop: wide('food-bg'), video: V.fun, cast: 'Julia Ramos, Ben Cho', synopsis: 'A feared restaurant critic loses her sense of taste and must relearn food — and humility — working in a food truck.', episodes: [ep('S1 E1 — One Star', '28m', 'fc1', V.fun)] },
  { id: 'series-5', title: 'Night Protocol', category: 'series', genres: ['Action', 'Spy'], year: 2023, rating: 8.6, maturity: 'TV-MA', seasons: 2, episodesCount: 16, trending: 10, poster: pic('night-proto'), backdrop: wide('night-bg'), video: V.joy, cast: 'Sam Carter, Yara Ali', synopsis: 'A sleeper agent activated after 10 quiet years must decide whether the voice on the phone is still her agency.', episodes: [ep('E1 — Wake Up Call', '48m', 'np1', V.joy)] },
  { id: 'series-6', title: 'Golden Hour ER', category: 'series', genres: ['Drama', 'Medical'], year: 2024, rating: 8.2, maturity: 'TV-14', seasons: 1, episodesCount: 10, poster: pic('golden-er'), backdrop: wide('golden-bg'), video: V.melt, cast: 'Diverse ensemble', synopsis: 'Overworked ER doctors race the clock in the critical first hour after trauma — while their own lives fall apart.', episodes: [ep('E1 — Code Blue', '44m', 'ge1', V.melt)] },
  // ANIMATION
  { id: 'anim-1', title: 'Captain Comet & Pip', category: 'animation', genres: ['Kids', 'Adventure', 'Comedy'], year: 2024, rating: 8.7, maturity: 'TV-Y7', seasons: 2, episodesCount: 40, lang: 'English', trending: 3, poster: pic('comet'), backdrop: wide('comet-bg'), video: V.bunny, cast: 'Voice: Tara Strong-style', synopsis: 'A kid star-captain and his robot blob sidekick explore planets, fix mix-ups and learn big feelings.', episodes: [ep('E1 — The Wobbly Planet', '22m', 'cc1', V.bunny), ep('E2 — Pip Gets Hiccups', '22m', 'cc2', V.fun)] },
  { id: 'anim-2', title: 'Dragon Bakery', category: 'animation', genres: ['Family', 'Fantasy'], year: 2023, rating: 9.0, maturity: 'TV-G', seasons: 1, episodesCount: 20, trending: 6, poster: pic('dragon-bake'), backdrop: wide('dragon-bg'), video: V.dream, cast: 'Ensemble voices', synopsis: 'A young dragon runs a village bakery where enchanted bread solves townsfolk problems — with crumbs of chaos.', episodes: [ep('E1 — Sourdough Spell', '24m', 'db1', V.dream)] },
  { id: 'anim-3', title: 'Robo Pals: Junkyard Crew', category: 'animation', genres: ['Kids', 'Sci-Fi', 'Comedy'], year: 2024, rating: 8.3, maturity: 'TV-Y', seasons: 1, episodesCount: 26, poster: pic('robo-pals'), backdrop: wide('robo-bg'), video: V.escapes, cast: 'Voice ensemble', synopsis: 'Misfit scrap robots build wild inventions from junk and enter the big Robot Rally.', episodes: [ep('E1 — Bolts & Friends', '22m', 'rp1', V.escapes)] },
  { id: 'anim-4', title: 'The Inkworld Tales', category: 'animation', genres: ['Fantasy', 'Adventure'], year: 2022, rating: 8.9, maturity: 'TV-PG', seasons: 2, episodesCount: 24, poster: pic('inkworld'), backdrop: wide('ink-bg'), video: V.sintel, cast: 'Award-winning voices', synopsis: 'Drawings leap off the page in a magical library where a brother and sister must finish an unfinished story.', episodes: [ep('E1 — Page One', '26m', 'iw1', V.sintel)] },
  { id: 'anim-5', title: 'Sushi Squad', category: 'animation', genres: ['Comedy', 'Kids'], year: 2023, rating: 7.8, maturity: 'TV-Y7', seasons: 3, episodesCount: 52, poster: pic('sushi'), backdrop: wide('sushi-bg'), video: V.joy, cast: 'Comic voices', synopsis: 'A team of living sushi pieces fights kitchen villains with chopstick kung-fu.', episodes: [ep('E1 — Wasabi Warning', '11m', 'ss1', V.joy)] },
  { id: 'anim-6', title: 'Mythic Pets', category: 'animation', genres: ['Family', 'Fantasy', 'Comedy'], year: 2024, rating: 8.5, maturity: 'TV-G', seasons: 1, episodesCount: 18, poster: pic('mythic'), backdrop: wide('mythic-bg'), video: V.fun, cast: 'Family cast', synopsis: 'A girl opens a shelter for baby mythical creatures — griffins, kelpies and one very dramatic phoenix.', episodes: [ep('E1 — Adopt a Griffin', '23m', 'mp1', V.fun)] },
];

export const categories = [
  { id: 'anime', label: 'Anime', desc: 'Subbed & dubbed series, films and simulcasts', grad: 'linear-gradient(135deg,#ec4899,#7c3aed)' },
  { id: 'movie', label: 'Movies', desc: 'Blockbusters, thrillers, romance & epics', grad: 'linear-gradient(135deg,#e50914,#f59e0b)' },
  { id: 'series', label: 'TV Series', desc: 'Binge-worthy dramas, crime & sci-fi', grad: 'linear-gradient(135deg,#0ea5e9,#22c55e)' },
  { id: 'animation', label: 'Animation', desc: 'Family, kids & all-ages adventures', grad: 'linear-gradient(135deg,#f59e0b,#10b981)' },
  { id: 'manga', label: 'Manga', desc: 'Read trending manga via AniList + MKissa', grad: 'linear-gradient(135deg,#ec4899,#f59e0b)' },
];

export const allGenres = [...new Set(catalog.flatMap((t) => t.genres))].sort();
export const getById = (id) => catalog.find((t) => t.id === id);
export const byCat = (cat) => catalog.filter((t) => t.category === cat);
export const trending = [...catalog].filter((t) => t.trending).sort((a, b) => a.trending - b.trending);
